;;; snow-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from snow.el

(autoload 'snow "snow" "\
Let it snow!
If already snowing, stop.  If MANUAL (interactively, with
prefix), advance snow frames manually by pressing \"SPC\".

(fn &optional MANUAL)" t)
(register-definition-prefixes "snow" '("snow-"))

;;; End of scraped data

(provide 'snow-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; snow-autoloads.el ends here
